### ISSUE TITLE
Audio sound card for 2 microphones

### ISSUE THREAD

**Issue by dumblob** [starcat-io/jupiter-nano-tools#2]
I'd like to buy some of these, but I'd need working ALSA sound card for recording from 2 microphones (I don't care how to connect them - last time I've soldered them directly to the board).

Do you plan to support sound card with at least two mics out of the box?

**Comment by adamfeuer** [comment]
@dumblob You should be able to use a USB sound card that supports ALSA, connected either to the Native USB port which has a MicroUSB connector; or to the native USB port B on the header connector. There's no header connected, you would have to solder one to use it. The USB port B cable kit includes everything you need there. You just install Linux ALSA drivers, I think.

Will that work for you?

**Comment by dumblob** [comment]
I'm not sure about the power consumption of the "power hungry" USB connection. Do you know of any USB sound card which is small and supports two microphones so that I could test the power consumption?

I've made a short lookup and couldn't find anything with two microphones or alternatively two **tiny** sound cards (each for one microphone).

**Comment by adamfeuer** [comment]
Not sure, you can definitely use two USB sound cards together.

There is this one:

**Comment by adamfeuer** [comment]
Not sure, you can definitely use two USB sound cards together.

There is this one:
https://www.newegg.com/p/36F-0043-00006

I searched for "USB sound card 2 microphones" on AliExpress and found some there too.

I get what you're saying about power consumption. You could use the internal 12-bit ADCs as audio inputs, not sure if that's enough resolution.

Or you could try these Teensy audio cards:

https://www.pjrc.com/store/teensy3_audio.html

Does that help?

**Comment by dumblob** [comment]
Thanks for the tips. Yes I found similar USB sound cards, but they're huge for my use case (I'd need to disassemble them, desolder connectors, then stack it on top of Jupiter Nano somehow - probably using some flex cable... - and even then I'd probably end up with bigger dimensions than Jupiter Nano itself while consuming quite a lot of power).

And the teensy audio cards don't have any drivers in Linux and it's not easy to write one for Linux from scratch (my friend - a kernel hacker - did something similar and it was an extreme PITA and the result was thousands of lines of code :open_mouth:).

I've looked up some other SBCs and SoMs and either they support no mic or only one mic or they're huge. I actually think mic inputs have more hacker use cases than one would imagine with GPIOs and other pins (last time I've seen display color calibration SW for Android using microphone with a ~1$ DIY tool). So sacrificing 4 pins (2 microphones where each needs 2 pins) on SBCs and SoMs would make sense to me, but it seems I'm dreaming :cry:.

Anyway, thanks for your help. I'll close this as "won't fix".

**Comment by adamfeuer** [comment]
@dumblob The Teensy audio cards use the [NXP SGL5000](https://www.nxp.com/products/audio-and-radio/audio-converters/ultra-low-power-audio-codec:SGTL5000) chip. There are Linux drivers for it in mainline:

https://github.com/torvalds/linux/blob/master/sound/soc/codecs/sgtl5000.c

Was there some reason you can't use that?

**Comment by dumblob** [comment]
@adamfeuer thanks, I missed that. Do you think no "glue kernel code" will be needed (except for DTB which is of course a must)? Because e.g. the `tlv320aic32x4` codec required writing about 1000 SLOC glue code on top of an existing kernel driver and of course an additional DTB section.

For SGTL5000 I found a similar question https://community.nxp.com/t5/i-MX-Processors/Linux-Drivers-for-SGTL5000/m-p/646659/highlight/true#M98765 and the answer is essentially "yes, you have to write quite a lot of glue code for SGTL5000".

**Comment by adamfeuer** [comment]
You will definitely need a DTS/DTB. I am not sure what glue code you are referring to... the SGTL5000 works with ALSA... can you say more about what you mean by glue code?

I have another idea... this board is supported by Microchip's SAMA5D27C Linux SDK:

https://www.mikroe.com/audio-codec-proto-board

You can find out more about that here:

https://www.linux4sam.org/bin/view/Linux4SAM/UsingI2SC

It's also in the Linux mainline tree:

https://github.com/torvalds/linux/blob/master/sound/soc/codecs/wm8731.c

The chip is the wm8731 which has stereo in and out using I2SC:

https://www.cirrus.com/products/wm8731/

**Comment by adamfeuer** [comment]
@dumblob You will definitely need a DTS/DTB. I am not sure what glue code you are referring to... the SGTL5000 works with ALSA... can you say more about what you mean by glue code?

I have another idea... this board is supported by Microchip's SAMA5D27C Linux SDK:

https://www.mikroe.com/audio-codec-proto-board

You can find out more about that here:

https://www.linux4sam.org/bin/view/Linux4SAM/UsingI2SC

It's also in the Linux mainline tree:

https://github.com/torvalds/linux/blob/master/sound/soc/codecs/wm8731.c

The chip is the wm8731 which has stereo in and out using I2SC:

https://www.cirrus.com/products/wm8731/

**Comment by dumblob** [comment]
> @dumblob You will definitely need a DTS/DTB. I am not sure what glue code you are referring to... the SGTL5000 works with ALSA... can you say more about what you mean by glue code?

Sure. Usually it all boils down to 2 things: 1) some init after boot (usually over I2C) and 2) changes during runtime (e.g. volume) - again usually over I2C.

Take a look at the link I've mentioned: https://community.nxp.com/t5/i-MX-Processors/Linux-Drivers-for-SGTL5000/m-p/646659/highlight/true#M98765 . It says `codec + i.MX specific`. Linux has the `codec` part, but doesn't have the `i.MX specific` part (because `i.MX` platform is not generic and each board has it slightly differently). And this `i.MX specific` part is what I was referring to `glue code`. This `Jupiter Nano specific` has to be written for Jupiter Nano. And I expect it to be 1000-3000 SLOC of a bit tedious work (there can be many different issues with sound cards from my experience and it's not easy to catch them - one has to run hours-long sessions of tests to have some base level of confidence).

> I have another idea... this board is supported by Microchip's SAMA5D27C Linux SDK:
> 
> https://www.mikroe.com/audio-codec-proto-board
> 
> You can find out more about that here:
> 
> https://www.linux4sam.org/bin/view/Linux4SAM/UsingI2SC
> 
> It's also in the Linux mainline tree:
> 
> https://github.com/torvalds/linux/blob/master/sound/soc/codecs/wm8731.c
> 
> The chip is the wm8731 which has stereo in and out using I2SC:
> 
> https://www.cirrus.com/products/wm8731/

This all sounds too great to be true :wink:. Could you clarify why do you think `SAMA5D27` is the same as `SAMA5D2`? From my experience it's two different SoC series mutually incompatible. To be specific, I couldn't find any information about `SAMA5D27` having the I2SC built in. If so, then it seems to be missing support in Linux.

**Comment by adamfeuer** [comment]
@dumblob The SAMA5D2_Xplained uses a SAMA5D27C just like Jupiter Nano. They're even clocked at the same speed. So this software should just work as long as you set up the DTS/DTB like their example, maybe changing the GPIO pins to match the Jupiter Nano's I2S port.

**Comment by adamfeuer** [comment]
@dumblob Here's the [SAMA5D2 datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/DS60001476B.pdf). All these chips share the same peripherals, except for some security features.

The Inter-IC Sound Controller documentation is located in Section 44. You can see which pins are dedicated to the I2SC ports in Section 6, Package and Pinout. The [SAMA5D27C-LD1G has a different pinout, you can see that in the SIP datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/SAMA5D2-Plus-DDR2-LPDDR2-System-in-Package-(SIP)-60001484b.pdf).
